### ISSUE TITLE
Dataset and how to train?

### ISSUE THREAD

**Issue by ilwoonam75** [glkuzi/SceneChangeDetectionNet#1]
Thank you for your work.
I want to know which dataset you use and how to train your model.

**Comment by glkuzi** [comment]
I'm sorry for so late answer. This project was made for hackathon, so it could be complicated to run it properly.
As I remember, to train model one has to load [this](http://www.vision.is.tohoku.ac.jp/us/download/) dataset, create several train and val .txt files with paths to images from t0, t1 and ground_truth directories. Names of this files could be found in main() function of model.py file. So after all this you only have to run `python3 model.py` and model training starts.
