### ISSUE TITLE
How should I position my data sets?

### ISSUE THREAD

**Issue by aishiliu** [glkuzi/SceneChangeDetectionNet#2]
Thank you for sharing your code!I want to know how should I position my data sets?Does this code need a label file?look forward to your reply .Thanks a lot!

**Comment by glkuzi** [comment]
This project was made for hackathon, so it is better to use it as some kind of baseline and modify by yourself.
If you want to run it with your own dataset, you can look at #1 - there is a comment, describing this model was trained. For some custom dataset, you could create .txt files for train and validation part with pathes to your images from ./dataset/ directory.

For example, in model.py in this string 
`patches_train = ['t0train.txt', 't1train.txt', 'gttrain.txt']`
defined patches to files with pathes to images from t0, t1 and ground_truth directories from [this](http://www.vision.is.tohoku.ac.jp/us/download/) dataset. So if you will use this dataset, you have to place t0, t1 and ground_truth directories to ./dataset/ directory, and add on the one level with model.py files with pathes from ./dataset/ directory.
